blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today', views.PostTAV.as_view(), name='post_today_archive'),
   
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>', views.TaggedObjectLV.as_view(), name='tagged_object_list'),

    path('search/', views.SearchFormView.as_view(), name='search'),


    path('add/',views.PostCreateView.as_view(), name="add",),
    path('change/',
         views.PostChangeLV.as_view(), name="change",
    ),
    path('<int:pk>/update/',
         views.PostUpdateView.as_view(), name="update",
    ),
    path('<int:pk>/delete/',
         views.PostDeleteView.as_view(), name="delete",
    ),
]




bookmark/urls.py
from django.urls import path
from bookmark import views

app_name = 'bookmark'  # 네임스페이스 name space  (이름 공간)
urlpatterns = [
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),
    path('add/', views.BookmarkCreateView.as_view(), name='add'),
    path('change/', views.BookmarkChangeLV.as_view(), name='change'),
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete'),
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path, include
from mysite.views import HomeView, UserCreateView, UserCreateDoneTV

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',  HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
     path('logout/', LogoutView.as_view(), name='logout'),
    # path('accounts/logout', LogoutView.as_view(next_page="/blog"), name='logout'),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    path('bookmark/', include('bookmark.urls')),
    path('blog/', include('blog.urls')),
    path('photo/', include('photo.urls')),
]  

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

bookmark/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Bookmark(models.Model):
  title = models.CharField('TITLE', max_length=100, blank=True)
  url = models.URLField('URL', unique=True)
  owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

  def __str__(self):
    return self.title

bookmark/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from bookmark.models  import Bookmark
from django.views.generic import CreateView, UpdateView, DeleteView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin

# Create your views here.


class BookmarkLV(ListView):
  model = Bookmark

class BookmarkDV(DetailView):
  model = Bookmark



class BookmarkCreateView(LoginRequiredMixin, CreateView): 
    model = Bookmark 
    fields = ['title', 'url'] 
    success_url = reverse_lazy('bookmark:index') 

    def form_valid(self, form): 
        form.instance.owner = self.request.user 
        return super().form_valid(form) 


class BookmarkChangeLV(LoginRequiredMixin, ListView): 
    template_name = 'bookmark/bookmark_change_list.html' 

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)


class BookmarkUpdateView(OwnerOnlyMixin, UpdateView): 
    model = Bookmark 
    fields = ['title', 'url'] 
    success_url = reverse_lazy('bookmark:index') 


class BookmarkDeleteView(OwnerOnlyMixin, DeleteView): 
    model = Bookmark 
    success_url = reverse_lazy('bookmark:index')

templates/bookmark/bookmark_change_list.html
{% extends "base.html" %}

{% block title %}bookmark_change_list.html{% endblock %}

{% block content %}

    <h1>Bookmark Change - {{user}}</h1>

    <table class="table table-striped table-bordered table-condensed">

        <thead>
        <tr class="table-primary">
            <th>Title</th>
            <th>URL</th>
            <th>Owner</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
        </thead>

        <tbody>
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.url }}</td>
            <td>{{ item.owner }}</td>
            <td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
            <td><a href="{% url 'bookmark:delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
        </tbody>

    </table>

{% endblock %}

templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}

    <h1>Bookmark Delete</h1>
    <br>

    <form action="." method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>

</div>
{% endblock %}

templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <ul>
    <li><a href=" {{object.url}}"> {{object.title}}</a></li>
  </ul>
 <br>
</body>
</html>

templates/bookmark/bookmark_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}bookmark_form.html{% endblock %}

{% block content %}

    <h1>Bookmark Create</h1>
    <p class="font-italic">Please enter your bookmark title and URL.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">{% csrf_token %}

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.url|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.url|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Add" class="btn btn-info"/>
            </div>
        </div>

    </form>

{% endblock %}

templates/bookmark/bookmark_list.html

  {% extends 'base.html' %}

  {% block title %} 북마크_리스트.html   {% endblock %}


  {% block content %} 
  <h1> Bookmark List</h1>
  <br>
  <ul>
    {% for  bookmark  in object_list  %}
    <li><a href="{% url 'bookmark:detail' bookmark.id %}"> {{bookmark}} </a> </li>
    {% endfor %}
  </ul>
  {% endblock content %}
  